# Generated by Django 4.1.10 on 2023-08-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_accepted',
            field=models.BooleanField(default=False, help_text='Designates whether this user is accepted for registration.', verbose_name='Registration accepted'),
        ),
    ]
